plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.0'
	id 'io.spring.dependency-management' version '1.1.7'
}
// 1. Definición de variables centralizadas
ext {
    dcm4cheVersion = '5.35.0'
}
group = 'dit.us.derma'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
// 1. Repositorio oficial de dcm4che
    maven {
        url uri('https://www.dcm4che.org/maven2/')
    }
    
    // 2. Repositorio de Weasis (NECESARIO para resolver "weasis-core-img-bom")
    maven {
        url uri('https://raw.githubusercontent.com/nroduit/mvn-repo/master')
    }

    // 3. Repositorio de respaldo JBoss/Nexus
    maven {
        url uri('https://repository.jboss.org/nexus/content/groups/public/')
    }

}

dependencies {
	//implementation "jakarta.json:jakarta.json-api:2.1.3"

    // Proveedor runtime (necesario para que Json.createParser() funcione en ejecución)
    implementation "org.glassfish:javax.json:1.1.4"
	// Source: https://mvnrepository.com/artifact/org.dcm4che/dcm4che-core
	implementation "org.dcm4che:dcm4che-core:${dcm4cheVersion}"
	// Source: https://mvnrepository.com/artifact/org.dcm4che.tool/dcm4che-tool-common
	implementation "org.dcm4che.tool:dcm4che-tool-common:${dcm4cheVersion}"
	// Source: https://mvnrepository.com/artifact/org.dcm4che/dcm4che-net
	implementation "org.dcm4che:dcm4che-net:${dcm4cheVersion}"
	// Source: https://mvnrepository.com/artifact/org.dcm4che/dcm4che-json
	implementation "org.dcm4che:dcm4che-json:${dcm4cheVersion}"
	implementation "org.springframework.boot:spring-boot-starter-webmvc"
	developmentOnly "org.springframework.boot:spring-boot-devtools"
	testImplementation "org.springframework.boot:spring-boot-starter-webmvc-test"
	testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

tasks.named('test') {
	useJUnitPlatform()
}
