# ===================================================================
# Configuración del Servidor y Aplicación
# ===================================================================
server.port=8081
spring.application.name=task-performer

# ===================================================================
# Configuración del Task Manager (ej. DCM4CHEE Arc)
# ===================================================================
# URL base de los servicios REST/UPS-RS del Task Manager
taskmanager.dicomweb.url=http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs

# ===================================================================
# Configuración del Task Performer (Tu Microservicio)
# ===================================================================
# AE Title con el que se registrará y suscribirá la IA
taskperformer.aet=MY_DERMA_AI

# URL base donde el Task Manager enviará los Event Reports / Webhooks
taskperformer.notification-url=http://localhost:8081/api/v1/ups/events

# ===================================================================
# Niveles de Log
# ===================================================================
logging.level.root=INFO
logging.level.com.miempresa.taskperformer=DEBUG
logging.level.org.dcm4che3=INFO